package com.focus.qweb.to;

import java.util.HashMap;
import java.util.Map;

import com.focus.qweb.interfaces.ObjetoTO;

public class TransactionTO implements ObjetoTO {

	private static final long serialVersionUID = 1L;

	private int idTransaction;
	private String traDescrip;
	private int traGravity;
	private int traSave;
	private int traNotify;
	private String traTextHistory;
	private String traTextNotify;
	private String traPerformer;
	private String traCaseException;
	private String traEmail;
	private String traJsp;
	private String traLocation;
	private String traClass;
	private String traClassLocation;
	private int traActivate;
	private int traLevel;

	public TransactionTO() {
	}

	public int getIdTransaction() {
		return idTransaction;
	}

	public void setIdTransaction(int idTransaction) {
		this.idTransaction = idTransaction;
	}

	public String getTraDescrip() {
		return traDescrip;
	}

	public void setTraDescrip(String traDescrip) {
		this.traDescrip = traDescrip;
	}

	public int getTraGravity() {
		return traGravity;
	}

	public void setTraGravity(int traGravity) {
		this.traGravity = traGravity;
	}

	public int getTraSave() {
		return traSave;
	}

	public void setTraSave(int traSave) {
		this.traSave = traSave;
	}

	public int getTraNotify() {
		return traNotify;
	}

	public void setTraNotify(int traNotify) {
		this.traNotify = traNotify;
	}

	public String getTraTextHistory() {
		return traTextHistory;
	}

	public void setTraTextHistory(String traTextHistory) {
		this.traTextHistory = traTextHistory;
	}

	public String getTraTextNotify() {
		return traTextNotify;
	}

	public void setTraTextNotify(String traTextNotify) {
		this.traTextNotify = traTextNotify;
	}

	public String getTraPerformer() {
		return traPerformer;
	}

	public void setTraPerformer(String traPerformer) {
		this.traPerformer = traPerformer;
	}

	public String getTraCaseException() {
		return traCaseException;
	}

	public void setTraCaseException(String traCaseException) {
		this.traCaseException = traCaseException;
	}

	public String getTraEmail() {
		return traEmail;
	}

	public void setTraEmail(String traEmail) {
		this.traEmail = traEmail;
	}

	public String getTraJsp() {
		return traJsp;
	}

	public void setTraJsp(String traJsp) {
		this.traJsp = traJsp;
	}

	public String getTraLocation() {
		return traLocation;
	}

	public void setTraLocation(String traLocation) {
		this.traLocation = traLocation;
	}

	public String getTraClass() {
		return traClass;
	}

	public void setTraClass(String traClass) {
		this.traClass = traClass;
	}

	public String getTraClassLocation() {
		return traClassLocation;
	}

	public void setTraClassLocation(String traClassLocation) {
		this.traClassLocation = traClassLocation;
	}

	public int getTraActivate() {
		return traActivate;
	}

	public void setTraActivate(int traActivate) {
		this.traActivate = traActivate;
	}

	public int getTraLevel() {
		return traLevel;
	}

	public void setTraLevel(int traLevel) {
		this.traLevel = traLevel;
	}

	
	public static final String ELIMINAR_CARPETA = "10800"; //EditStructAction
	public static final String MOVER_CARPETA = "10700"; //EditStructAction
	public static final String MOVER_DOCUMENTO = "11200"; //EditStructAction
	public static final String PERMISOS_USUARIO_SOBRE_DOCUENTO = "11600";//EditSecurityStructUserAction
	public static final String PERMISOS_GRUPOS_SOBRE_DOCUMENTO = "11650";//EditSecurityStrucGroupAction
	public static final String DESCARGAR_DOCUMENTO = "11700";//ShowDataDocument
	public static final String CAMBIO_AREA = "92115";
	public static final String CAMBIO_CARGO = "92130";
	public static final String SUSTITUCION_USUARIO = "92145";
	public static final String ELIMINACION_USUARIO = "92160";
	
	public static final String EDITAR_CONFIGURACION = "95000";
	public static final String EDITAR_CONFIGURACION_INICIO_DE_SESION = "95100";
	public static final String EDITAR_CONFIGURACION_VIGENCIA_DE_CONTRASENA = "95105";
	public static final String EDITAR_CONFIGURACION_MINIMO_DE_CARACTERES_PARA_UNA_CONTRASENA = "95110";
	public static final String EDITAR_CONFIGURACION_TIEMPO_DE_EXPIRACION_DE_SESION = "95115";
	public static final String EDITAR_CONFIGURACION_TIEMPO_DE_EXPIRACION_PARA_EDICION = "95120";
	public static final String EDITAR_CONFIGURACION_SACOP = "95200";
	public static final String EDITAR_CONFIGURACION_TIEMPO_EN_DIAS_CON_QUE_SERA_NOTIFICADO_UN_USUARIO_QUE_ALGUNA_ACCION_DE_LA_SACOP_ESTA_POR_VENCER = "95205";
	public static final String EDITAR_CONFIGURACION_CANTIDAD_DE_DIAS_DE_INACTIVIDAD_DE_LA_SACOP_EMITIDA_PERO_NO_RESPONDIDA = "95210";
	public static final String EDITAR_CONFIGURACION_CANTIDAD_DE_DIAS_DE_LA_SACOP_ACEPTADA_PERO_SIN_EL_PLAN_DE_ACCION = "95215";
	public static final String EDITAR_CONFIGURACION_LISTA_DE_GESTIONADORES_SACOPS = "95220";
	public static final String EDITAR_CONFIGURACION_VIGENCIA_DE_SACOPS_CERRADAS = "95225";
	public static final String EDITAR_CONFIGURACION_MES_DE_CIERRE_ANUAL = "95230";
	public static final String EDITAR_CONFIGURACION_LIMITE_DE_MESES_DE_ANTIGUEDAD = "95235";
	public static final String EDITAR_CONFIGURACION_MOSTRAR_CARGO_DE_LOS_USUARIOS_SACOP = "95240";
	public static final String EDITAR_CONFIGURACION_NUMERACION_DEL_SISTEMA = "95245";
	public static final String EDITAR_CONFIGURACION_CORREO = "95300";
	public static final String EDITAR_CONFIGURACION_NOTIFICAR_POR_CORREO = "95305";
	public static final String EDITAR_CONFIGURACION_VALIDAR_FORMATO_DE_CORREO = "95310";
	public static final String EDITAR_CONFIGURACION_HABILITAR_DEBUG_DE_NOTIFICACIONES = "95315";
	public static final String EDITAR_CONFIGURACION_VALIDAR_DOMINIO_DE_CORREO = "95320";
	public static final String EDITAR_CONFIGURACION_SERVIDOR_DE_CORREO_SMTP_ESMTP = "95325";
	public static final String EDITAR_CONFIGURACION_PUERTO_DEL_SERVIDOR_DE_CORREO_SMTP_ESMTP = "95330";
	public static final String EDITAR_CONFIGURACION_CUENTA_DE_CORREO_DEL_REMITENTE_PARA_NOTIFICACIONES_DEL_SISTEMA = "95335";
	public static final String EDITAR_CONFIGURACION_CLAVE_DE_LA_CUENTA_DE_CORREO_PARA_NOTIFICACIONES_DEL_SISTEMA = "95340";
	public static final String EDITAR_CONFIGURACION_INDIQUE_EL_PROTOCOLO_DE_AUTENTICACION_PARA_LAS_NOTIFICACIONES = "95345";
	public static final String EDITAR_CONFIGURACION_SUFIJO_PARA_EL_ASUNTO = "95355";
	public static final String EDITAR_CONFIGURACION_EOC = "95400";
	public static final String EDITAR_CONFIGURACION_COMENTARIOS_DE_UNA_NUEVA_VERSION_OBLIGATORIOS = "95405";
	public static final String EDITAR_CONFIGURACION_PERMITIR_CAMBIAR_NOMBRE_Y_PROPIETARIO_A_DOCUMENTOS_EN_ESTADO_APROBADO = "95415";
	public static final String EDITAR_CONFIGURACION_PARTICIPACION_DEL_GENERADOR_EN_LOS_FLUJOS_DE_TRABAJO = "95425";
	public static final String EDITAR_CONFIGURACION_VIGENCIA_DE_DOCUMENTOS = "95435";
	public static final String EDITAR_CONFIGURACION_VIGENCIA_DE_BORRADORES = "95445";
	public static final String EDITAR_CONFIGURACION_FECHA_DE_RETENCION = "95455";
	public static final String EDITAR_CONFIGURACION_VIGENCIA_DE_RETENCION_DE_DOCUMENTOS = "95456";
	
	public static final String EDITAR_CONFIGURACION_SISTEMA_DE_CALIDAD = "95457";
	public static final String EDITAR_CONFIGURACION_LONGITUD_DEL_CORRELATIVO_EN_EL_CODIGO_DEL_DOCUMENTO = "95458";
	public static final String EDITAR_CONFIGURACION_INICIAR_CONTADOR_EN = "95459";
	public static final String EDITAR_CONFIGURACION_CODIGO_DE_LOS_DOCUMENTOS = "95460";
	public static final String EDITAR_CONFIGURACION_ORDENAR_ESTRUCTURA = "95461";
	
	public static final String EDITAR_CONFIGURACION_FLUJOS_DE_TRABAJO = "95500";
	public static final String EDITAR_CONFIGURACION_COMPLETAR_FLUJO_DE_TRABAJO_PARAMETRICO = "95505";
	public static final String EDITAR_CONFIGURACION_REASIGNAR_USUARIO_AL_RECHAZAR_UN_FLUJO_DE_TRABAJO_PARAMETRICO = "95515";
	public static final String EDITAR_CONFIGURACION_CREAR_DOCUMENTO_DE_SOPORTE_DE_RECHAZO_EN_UN_FLUJO_DE_TRABAJO_PARAMETRICO = "95525";
	
	public static final String EDITAR_CONFIGURACION_COPIAR_Y_PEGAR_EL_DOCUMENTO_EN_FLUJOS_DE_TRABAJO = "95526";
	public static final String EDITAR_CONFIGURACION_EDITAR_REGISTROS_EN_FLUJOS_DE_APROBACION = "95527";
	
	public static final String EDITAR_CONFIGURACION_AUTENTICACION_REQUERIDA_PARA_FIRMAR_FLUJOS_DE_TRABAJO = "95535";
	public static final String EDITAR_CONFIGURACION_VIGENCIA_EN_DIAS_FLUJOS_CANCELADOS_EN_PRINCIPAL = "95540";
	public static final String EDITAR_CONFIGURACION_RESPONSABLE_SOLICITUDES_DE_CAMBIO = "95545";
	public static final String EDITAR_CONFIGURACION_RESPONSABLE_SOLICITUDES_DE_ELIMINACION = "95550";
	public static final String EDITAR_CONFIGURACION_RESPONSABLE_SOLICITUDES_DE_IMPRESION = "95555";
	public static final String EDITAR_CONFIGURACION_IMPRESION = "95600";
	public static final String EDITAR_CONFIGURACION_LIBRE_IMPRESION_PARA_ADMIN_Y_PROPIETARIO_DE_DOCUMENTOS = "95605";
	public static final String EDITAR_CONFIGURACION_IMPRIMIR_ELABORADOR = "95610";
	public static final String EDITAR_CONFIGURACION_IMPRIMIR_EDITORES = "95615";
	public static final String EDITAR_CONFIGURACION_IMPRIMIR_REVISORES = "95620";
	public static final String EDITAR_CONFIGURACION_IMPRIMIR_EL_NUMERO_SOBRE_EL_DOCUMENTO = "95625";
	public static final String EDITAR_CONFIGURACION_IMPRIMIR_LA_VERSION_SOBRE_EL_DOCUMENTO = "95630";
	public static final String EDITAR_CONFIGURACION_IMPRIMIR_LA_FECHA_DE_APROBACION_SOBRE_EL_DOCUMENTO = "95635";
	public static final String EDITAR_CONFIGURACION_HABILITAR_INFORMACION_EN_COPIAS_CONTROLADAS_Y_NO_CONTROLADAS = "95640";
	public static final String EDITAR_CONFIGURACION_DESACTIVAR_CACHE_DE_DOCUMENTOS_CONVERTIDOS = "95645";
	public static final String EDITAR_CONFIGURACION_VALORES_PREDETERMINADOS_PARA_LA_IMPRESION_DE_DOCUMENTOS = "95650";
	public static final String EDITAR_CONFIGURACION_ENCABEZADO_DE_HOJA_DE_IMPRESION_TITULO = "95660";
	public static final String EDITAR_CONFIGURACION_ENCABEZADO_DE_HOJA_DE_IMPRESION_CODIGO = "95661";
	public static final String EDITAR_CONFIGURACION_ENCABEZADO_DE_HOJA_DE_IMPRESION_OTRO = "95665";
	public static final String EDITAR_CONFIGURACION_ENCABEZADO_DE_HOJA_DE_IMPRESIONIMAGEN_GIF = "95666";
	public static final String EDITAR_CONFIGURACION_OPERACION_DEL_SISTEMA = "95700";
	public static final String EDITAR_CONFIGURACION_NO_PERMITIR_ABRIR_Y_GUARDAR_DOCUMENTOS_EN_IE6 = "95705";
	public static final String EDITAR_CONFIGURACION_VISUALIZAR_DOCUMENTOS_EN_PDF = "95710";
	public static final String EDITAR_CONFIGURACION_PROGRAMA_PARA_CONVERTIR_A_PDF = "95712";
	public static final String EDITAR_CONFIGURACION_VISUALIZAR_DOCUMENTOS_EN_PDF_CON_OPENOFFICE_RUTA = "95716";
	public static final String EDITAR_CONFIGURACION_DOMINIO_PARA_ACTIVE_DIRECTORY = "95720";
	public static final String EDITAR_CONFIGURACION_URL_PARA_ACTIVE_DIRECTORY = "95721";
	public static final String EDITAR_CONFIGURACION_PERMITIR_DESCARGA_DE_ULTIMA_VERSION = "95723";
	public static final String EDITAR_CONFIGURACION_EXTENSIONES_MANEJADAS_CON_DOBLE_VERSION = "95725";
	public static final String EDITAR_CONFIGURACION_EXTENSIONES_DE_ARCHIVO_NO_EDITABLES = "95726";
	public static final String EDITAR_CONFIGURACION_EXTENSIONES_EN_VISOR_NATIVO = "95728";
	public static final String EDITAR_CONFIGURACION_NOMBRE_DE_LA_CARPETA_COMPARTIDA = "95730";
	public static final String EDITAR_CONFIGURACION_RUTA_DEL_REPOSITORIO_DE_ARCHIVOS_DEL_SISTEMA = "95731";
	public static final String EDITAR_CONFIGURACION_RUTA_DEL_REPOSITORIO_DE_ANEXOS_1 = "95736";
	public static final String EDITAR_CONFIGURACION_RUTA_DEL_REPOSITORIO_DE_ANEXOS_2 = "95740";
	public static final String EDITAR_CONFIGURACION_CAMPO_DE_ENLACE_PARA_LOS_ANEXOS = "95741";
	public static final String EDITAR_CONFIGURACION_PUBLICAR_EL_PRIMER_BORRADOR = "95745";
	public static final String EDITAR_CONFIGURACION_CAMBIO_DE_CAMPOS_ADICIONALES = "95750";
	public static final String EDITAR_CONFIGURACION_NORMA_DE_AUDITORIA = "95755";
	public static final String EDITAR_CONFIGURACION_MENSAJES = "95800";
	public static final String EDITAR_CONFIGURACION_DOCUMENTOS_EXPIRADOS = "95805";
	public static final String EDITAR_CONFIGURACION_DOCUMENTOS_BORRADORES_YA_EXPIRADOS = "95810";
	public static final String EDITAR_CONFIGURACION_FLUJOS_DE_TRABAJO_EXPIRADOS = "95815";
	public static final String EDITAR_CONFIGURACION_FLUJOS_DE_TRABAJO_EN_REVISION = "95820";
	public static final String EDITAR_CONFIGURACION_FLUJOS_DE_TRABAJO_APROBADOS = "95825";
	public static final String EDITAR_CONFIGURACION_FLUJOS_DE_TRABAJO_CANCELADOS = "95830";
	public static final String EDITAR_CONFIGURACION_SACOPS_ACCIONES_POR_VENCER = "95835";
	public static final String EDITAR_CONFIGURACION_SACOPS_ACCIONES_VENCIDAS = "95840";

	public static final Map<String,String> LIST_FIELDS_PARAMETERS = new HashMap<>();
	static {
		LIST_FIELDS_PARAMETERS.put("lengthPass", EDITAR_CONFIGURACION_MINIMO_DE_CARACTERES_PARA_UNA_CONTRASENA);
		LIST_FIELDS_PARAMETERS.put("allowDuplicatePass", EDITAR_CONFIGURACION); // INTERNO
		LIST_FIELDS_PARAMETERS.put("expirePass", EDITAR_CONFIGURACION_VIGENCIA_DE_CONTRASENA);
		LIST_FIELDS_PARAMETERS.put("notifyEmail", EDITAR_CONFIGURACION_NOTIFICAR_POR_CORREO);
		LIST_FIELDS_PARAMETERS.put("smtpMail", EDITAR_CONFIGURACION_SERVIDOR_DE_CORREO_SMTP_ESMTP);
		LIST_FIELDS_PARAMETERS.put("qualitySystem", EDITAR_CONFIGURACION_SISTEMA_DE_CALIDAD);
		LIST_FIELDS_PARAMETERS.put("versionCom", EDITAR_CONFIGURACION_COMENTARIOS_DE_UNA_NUEVA_VERSION_OBLIGATORIOS);
		LIST_FIELDS_PARAMETERS.put("logDoc", EDITAR_CONFIGURACION);
		LIST_FIELDS_PARAMETERS.put("allowWF", EDITAR_CONFIGURACION_PARTICIPACION_DEL_GENERADOR_EN_LOS_FLUJOS_DE_TRABAJO);
		LIST_FIELDS_PARAMETERS.put("docNumber", EDITAR_CONFIGURACION);
		LIST_FIELDS_PARAMETERS.put("lengthDocNumber", EDITAR_CONFIGURACION_LONGITUD_DEL_CORRELATIVO_EN_EL_CODIGO_DEL_DOCUMENTO);
		LIST_FIELDS_PARAMETERS.put("resetDocNumber", EDITAR_CONFIGURACION_INICIAR_CONTADOR_EN);
		LIST_FIELDS_PARAMETERS.put("daysEndPass", EDITAR_CONFIGURACION_VIGENCIA_DE_CONTRASENA);
		LIST_FIELDS_PARAMETERS.put("expireDoc", EDITAR_CONFIGURACION_VIGENCIA_DE_DOCUMENTOS);
		LIST_FIELDS_PARAMETERS.put("monthExpireDoc", EDITAR_CONFIGURACION_VIGENCIA_DE_DOCUMENTOS);
		LIST_FIELDS_PARAMETERS.put("unitTimeExpire", EDITAR_CONFIGURACION_VIGENCIA_DE_DOCUMENTOS);
		LIST_FIELDS_PARAMETERS.put("endsession", EDITAR_CONFIGURACION_TIEMPO_DE_EXPIRACION_DE_SESION);
		LIST_FIELDS_PARAMETERS.put("typePrefix", EDITAR_CONFIGURACION);
		LIST_FIELDS_PARAMETERS.put("expireDrafts", EDITAR_CONFIGURACION_VIGENCIA_DE_BORRADORES);
		LIST_FIELDS_PARAMETERS.put("monthsExpireDrafts", EDITAR_CONFIGURACION_VIGENCIA_DE_BORRADORES);
		LIST_FIELDS_PARAMETERS.put("unitTimeExpireDrafts", EDITAR_CONFIGURACION_VIGENCIA_DE_BORRADORES);
		LIST_FIELDS_PARAMETERS.put("numByLocation", EDITAR_CONFIGURACION_CODIGO_DE_LOS_DOCUMENTOS);
		LIST_FIELDS_PARAMETERS.put("typeNumByLocation", EDITAR_CONFIGURACION);
		LIST_FIELDS_PARAMETERS.put("cargosacop", EDITAR_CONFIGURACION_MOSTRAR_CARGO_DE_LOS_USUARIOS_SACOP);
		LIST_FIELDS_PARAMETERS.put("typeOrden", EDITAR_CONFIGURACION_ORDENAR_ESTRUCTURA);
		LIST_FIELDS_PARAMETERS.put("idioma", EDITAR_CONFIGURACION);
		LIST_FIELDS_PARAMETERS.put("validateEmail", EDITAR_CONFIGURACION_VALIDAR_FORMATO_DE_CORREO);
		LIST_FIELDS_PARAMETERS.put("printOwnerAdmin", EDITAR_CONFIGURACION_LIBRE_IMPRESION_PARA_ADMIN_Y_PROPIETARIO_DE_DOCUMENTOS);
		LIST_FIELDS_PARAMETERS.put("completeFTP", EDITAR_CONFIGURACION_COMPLETAR_FLUJO_DE_TRABAJO_PARAMETRICO);
		LIST_FIELDS_PARAMETERS.put("msgWFCompletados", EDITAR_CONFIGURACION);
		LIST_FIELDS_PARAMETERS.put("viewReaders", EDITAR_CONFIGURACION_IMPRIMIR_REVISORES);
		LIST_FIELDS_PARAMETERS.put("reasigneUserFTP", EDITAR_CONFIGURACION_REASIGNAR_USUARIO_AL_RECHAZAR_UN_FLUJO_DE_TRABAJO_PARAMETRICO);
		LIST_FIELDS_PARAMETERS.put("downloadLastVer", EDITAR_CONFIGURACION_PERMITIR_DESCARGA_DE_ULTIMA_VERSION); 
		LIST_FIELDS_PARAMETERS.put("impNameCharge", EDITAR_CONFIGURACION_VALORES_PREDETERMINADOS_PARA_LA_IMPRESION_DE_DOCUMENTOS);
		LIST_FIELDS_PARAMETERS.put("headImp1", EDITAR_CONFIGURACION_ENCABEZADO_DE_HOJA_DE_IMPRESION_TITULO);
		LIST_FIELDS_PARAMETERS.put("headImp2", EDITAR_CONFIGURACION_ENCABEZADO_DE_HOJA_DE_IMPRESION_CODIGO);
		LIST_FIELDS_PARAMETERS.put("headImp3", EDITAR_CONFIGURACION_ENCABEZADO_DE_HOJA_DE_IMPRESION_OTRO);
		LIST_FIELDS_PARAMETERS.put("validNavigator", EDITAR_CONFIGURACION);
		LIST_FIELDS_PARAMETERS.put("fileNotOpenSave", EDITAR_CONFIGURACION);
		LIST_FIELDS_PARAMETERS.put("fileDoubleVersion", EDITAR_CONFIGURACION_EXTENSIONES_MANEJADAS_CON_DOBLE_VERSION);
		LIST_FIELDS_PARAMETERS.put("mailAccount", EDITAR_CONFIGURACION_CUENTA_DE_CORREO_DEL_REMITENTE_PARA_NOTIFICACIONES_DEL_SISTEMA);
		LIST_FIELDS_PARAMETERS.put("openoffice", EDITAR_CONFIGURACION_VISUALIZAR_DOCUMENTOS_EN_PDF);
		LIST_FIELDS_PARAMETERS.put("endSessionEdit", EDITAR_CONFIGURACION_TIEMPO_DE_EXPIRACION_PARA_EDICION);
		LIST_FIELDS_PARAMETERS.put("domainEmail", EDITAR_CONFIGURACION_VALIDAR_DOMINIO_DE_CORREO);
		LIST_FIELDS_PARAMETERS.put("documentReject", EDITAR_CONFIGURACION_CREAR_DOCUMENTO_DE_SOPORTE_DE_RECHAZO_EN_UN_FLUJO_DE_TRABAJO_PARAMETRICO);
		LIST_FIELDS_PARAMETERS.put("viewCreator", EDITAR_CONFIGURACION_IMPRIMIR_ELABORADOR);
		LIST_FIELDS_PARAMETERS.put("viewCollaborator", EDITAR_CONFIGURACION_IMPRIMIR_EDITORES);
		LIST_FIELDS_PARAMETERS.put("viewpdftool", EDITAR_CONFIGURACION_PROGRAMA_PARA_CONVERTIR_A_PDF);
		LIST_FIELDS_PARAMETERS.put("oooExeFolder", EDITAR_CONFIGURACION_VISUALIZAR_DOCUMENTOS_EN_PDF_CON_OPENOFFICE_RUTA);
		LIST_FIELDS_PARAMETERS.put("changeProperties", EDITAR_CONFIGURACION_PERMITIR_CAMBIAR_NOMBRE_Y_PROPIETARIO_A_DOCUMENTOS_EN_ESTADO_APROBADO);
		LIST_FIELDS_PARAMETERS.put("fileDeadFile", EDITAR_CONFIGURACION);
		LIST_FIELDS_PARAMETERS.put("fileDeadTime", EDITAR_CONFIGURACION);
		LIST_FIELDS_PARAMETERS.put("fileDeadUnit", EDITAR_CONFIGURACION);
		LIST_FIELDS_PARAMETERS.put("fileDeadVerbose", EDITAR_CONFIGURACION);
		LIST_FIELDS_PARAMETERS.put("fileUploadVersion", EDITAR_CONFIGURACION_EXTENSIONES_DE_ARCHIVO_NO_EDITABLES);
		LIST_FIELDS_PARAMETERS.put("printVersion", EDITAR_CONFIGURACION_IMPRIMIR_LA_VERSION_SOBRE_EL_DOCUMENTO);
		LIST_FIELDS_PARAMETERS.put("printNumber", EDITAR_CONFIGURACION_IMPRIMIR_EL_NUMERO_SOBRE_EL_DOCUMENTO);
		LIST_FIELDS_PARAMETERS.put("folderCmp", EDITAR_CONFIGURACION_NOMBRE_DE_LA_CARPETA_COMPARTIDA);
		LIST_FIELDS_PARAMETERS.put("editorOnDemand", EDITAR_CONFIGURACION);
		LIST_FIELDS_PARAMETERS.put("editOriginatorWF", EDITAR_CONFIGURACION_EDITAR_REGISTROS_EN_FLUJOS_DE_APROBACION);
		LIST_FIELDS_PARAMETERS.put("domain", EDITAR_CONFIGURACION_DOMINIO_PARA_ACTIVE_DIRECTORY);
		LIST_FIELDS_PARAMETERS.put("ldapurl", EDITAR_CONFIGURACION_URL_PARA_ACTIVE_DIRECTORY);
		LIST_FIELDS_PARAMETERS.put("repository", EDITAR_CONFIGURACION_RUTA_DEL_REPOSITORIO_DE_ARCHIVOS_DEL_SISTEMA);
		LIST_FIELDS_PARAMETERS.put("copyContents", EDITAR_CONFIGURACION_COPIAR_Y_PEGAR_EL_DOCUMENTO_EN_FLUJOS_DE_TRABAJO);
		LIST_FIELDS_PARAMETERS.put("numberSacop", EDITAR_CONFIGURACION);
		LIST_FIELDS_PARAMETERS.put("postfixMail", EDITAR_CONFIGURACION_SUFIJO_PARA_EL_ASUNTO);
		LIST_FIELDS_PARAMETERS.put("deadDoc", EDITAR_CONFIGURACION_FECHA_DE_RETENCION);
		LIST_FIELDS_PARAMETERS.put("monthsDeadDocs", EDITAR_CONFIGURACION_VIGENCIA_DE_RETENCION_DE_DOCUMENTOS);
		LIST_FIELDS_PARAMETERS.put("unitTimeDead", EDITAR_CONFIGURACION_VIGENCIA_DE_RETENCION_DE_DOCUMENTOS);
		LIST_FIELDS_PARAMETERS.put("disabledCache", EDITAR_CONFIGURACION);
		LIST_FIELDS_PARAMETERS.put("attachedFolder0", EDITAR_CONFIGURACION_RUTA_DEL_REPOSITORIO_DE_ANEXOS_1);
		LIST_FIELDS_PARAMETERS.put("attachedFolder1", EDITAR_CONFIGURACION_RUTA_DEL_REPOSITORIO_DE_ANEXOS_2);
		LIST_FIELDS_PARAMETERS.put("attachedField", EDITAR_CONFIGURACION_CAMPO_DE_ENLACE_PARA_LOS_ANEXOS);
		LIST_FIELDS_PARAMETERS.put("publicEraser", EDITAR_CONFIGURACION_PUBLICAR_EL_PRIMER_BORRADOR);
		LIST_FIELDS_PARAMETERS.put("changeAditionalField", EDITAR_CONFIGURACION_CAMBIO_DE_CAMPOS_ADICIONALES);
		LIST_FIELDS_PARAMETERS.put("printApprovedDate", EDITAR_CONFIGURACION_IMPRIMIR_LA_FECHA_DE_APROBACION_SOBRE_EL_DOCUMENTO);
		LIST_FIELDS_PARAMETERS.put("mail_auth_protocol", EDITAR_CONFIGURACION_INDIQUE_EL_PROTOCOLO_DE_AUTENTICACION_PARA_LAS_NOTIFICACIONES);
		LIST_FIELDS_PARAMETERS.put("mail_smtp_port", EDITAR_CONFIGURACION_PUERTO_DEL_SERVIDOR_DE_CORREO_SMTP_ESMTP);
		LIST_FIELDS_PARAMETERS.put("mail_auth_password", EDITAR_CONFIGURACION_CLAVE_DE_LA_CUENTA_DE_CORREO_PARA_NOTIFICACIONES_DEL_SISTEMA);
		LIST_FIELDS_PARAMETERS.put("mail_enable_debug", EDITAR_CONFIGURACION_HABILITAR_DEBUG_DE_NOTIFICACIONES);
		LIST_FIELDS_PARAMETERS.put("vigencia_flujos_cancelados", EDITAR_CONFIGURACION_VIGENCIA_EN_DIAS_FLUJOS_CANCELADOS_EN_PRINCIPAL);
		LIST_FIELDS_PARAMETERS.put("piePaginaWaterMark", EDITAR_CONFIGURACION_HABILITAR_INFORMACION_EN_COPIAS_CONTROLADAS_Y_NO_CONTROLADAS);
		LIST_FIELDS_PARAMETERS.put("diasAlertaAccionesSacopPorVencer", EDITAR_CONFIGURACION_TIEMPO_EN_DIAS_CON_QUE_SERA_NOTIFICADO_UN_USUARIO_QUE_ALGUNA_ACCION_DE_LA_SACOP_ESTA_POR_VENCER);
		LIST_FIELDS_PARAMETERS.put("autenticarflujo", EDITAR_CONFIGURACION_AUTENTICACION_REQUERIDA_PARA_FIRMAR_FLUJOS_DE_TRABAJO);
		LIST_FIELDS_PARAMETERS.put("respsolcambio", EDITAR_CONFIGURACION_RESPONSABLE_SOLICITUDES_DE_CAMBIO);
		LIST_FIELDS_PARAMETERS.put("respsolelimin", EDITAR_CONFIGURACION_RESPONSABLE_SOLICITUDES_DE_ELIMINACION);
		LIST_FIELDS_PARAMETERS.put("respsolimpres", EDITAR_CONFIGURACION_RESPONSABLE_SOLICITUDES_DE_IMPRESION);
		LIST_FIELDS_PARAMETERS.put("respsolsacop", EDITAR_CONFIGURACION);
		LIST_FIELDS_PARAMETERS.put("numberDaysInactivitySACOP", EDITAR_CONFIGURACION_CANTIDAD_DE_DIAS_DE_INACTIVIDAD_DE_LA_SACOP_EMITIDA_PERO_NO_RESPONDIDA);
		LIST_FIELDS_PARAMETERS.put("numberDaysWithoutActionSACOP", EDITAR_CONFIGURACION_CANTIDAD_DE_DIAS_DE_LA_SACOP_ACEPTADA_PERO_SIN_EL_PLAN_DE_ACCION);
		LIST_FIELDS_PARAMETERS.put("listUserAddressee", EDITAR_CONFIGURACION_LISTA_DE_GESTIONADORES_SACOPS);
		LIST_FIELDS_PARAMETERS.put("validitySacop", EDITAR_CONFIGURACION_VIGENCIA_DE_SACOPS_CERRADAS);
		LIST_FIELDS_PARAMETERS.put("validitySacopType", EDITAR_CONFIGURACION_LIMITE_DE_MESES_DE_ANTIGUEDAD);
		LIST_FIELDS_PARAMETERS.put("validitySacopMonth", EDITAR_CONFIGURACION_MES_DE_CIERRE_ANUAL);
		LIST_FIELDS_PARAMETERS.put("idNormAudit", EDITAR_CONFIGURACION_NORMA_DE_AUDITORIA);
		LIST_FIELDS_PARAMETERS.put("fileNativeViewer", EDITAR_CONFIGURACION_EXTENSIONES_EN_VISOR_NATIVO);

		// mensajes
		LIST_FIELDS_PARAMETERS.put("msgDocExpirado", EDITAR_CONFIGURACION_DOCUMENTOS_EXPIRADOS);
		LIST_FIELDS_PARAMETERS.put("msgWFBorrador", EDITAR_CONFIGURACION_DOCUMENTOS_BORRADORES_YA_EXPIRADOS);
		LIST_FIELDS_PARAMETERS.put("msgWFExpires", EDITAR_CONFIGURACION_FLUJOS_DE_TRABAJO_EXPIRADOS);
		LIST_FIELDS_PARAMETERS.put("msgWFCancelados", EDITAR_CONFIGURACION_FLUJOS_DE_TRABAJO_CANCELADOS);
		LIST_FIELDS_PARAMETERS.put("msgWFAprobados", EDITAR_CONFIGURACION_FLUJOS_DE_TRABAJO_APROBADOS);
		LIST_FIELDS_PARAMETERS.put("msgWFRevision", EDITAR_CONFIGURACION_FLUJOS_DE_TRABAJO_EN_REVISION);
		LIST_FIELDS_PARAMETERS.put("msgSacopAccionesPorVencer", EDITAR_CONFIGURACION_SACOPS_ACCIONES_POR_VENCER);
		LIST_FIELDS_PARAMETERS.put("msgSacopAccionesVencidas", EDITAR_CONFIGURACION_SACOPS_ACCIONES_VENCIDAS);

	}
	
	
	
}


